import { cn } from "@/lib/utils"
import "./globals.css"
import { Inter } from "next/font/google"

import ThemeProvider from "@/context/ThemeProvider"
import ThemeButton from "@/components/theme-button"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={cn("min-h-screen flex flex-col relative", inter.className)}
      >
        <ThemeProvider>
          {children}
          <ThemeButton />
        </ThemeProvider>
      </body>
    </html>
  )
}
